from fpdf import FPDF
import os
import datetime

def officer_node(state: dict):
    anomalies = state.get('anomalies', [])
    risk_score = state.get('risk_score', 0)
    filename = state.get('filename', 'report')
    
    pdf = FPDF()
    pdf.add_page()
    
    # En-tête
    pdf.set_font("Arial", "B", 16)
    pdf.cell(40, 10, "LucidAI - Audit Report", 0, 1)
    pdf.set_font("Arial", "I", 10)
    pdf.cell(40, 10, f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1)
    pdf.cell(40, 10, f"Source: {filename}", 0, 1)
    pdf.ln(10)
    
    # Score de risque
    pdf.set_font("Arial", "B", 14)
    risk_color = "0,0,0"
    if risk_score > 70:
        risk_color = "255,0,0"  # Red
    elif risk_score > 40:
        risk_color = "255,165,0"  # Orange
    else:
        risk_color = "0,128,0"  # Green
    
    pdf.set_text_color(0, 0, 0)
    pdf.cell(40, 10, f"Risk Score: {risk_score} / 100", 0, 1)
    pdf.ln(5)
    
    # Liste des anomalies
    pdf.set_font("Arial", "B", 12)
    pdf.cell(40, 10, f"Total Anomalies Detected: {len(anomalies)}", 0, 1)
    pdf.ln(5)
    
    pdf.set_font("Arial", "", 10)
    for idx, anom in enumerate(anomalies[:20]):  # Max 20 pour le rapport
        sev = anom.get('severity', 'unknown').upper()
        desc = anom.get('description', 'No description')
        pdf.multi_cell(0, 6, f"{idx+1}. [{sev}] {desc}", 0, 1)
    
    if len(anomalies) > 20:
        pdf.cell(40, 10, f"... and {len(anomalies)-20} more anomalies.", 0, 1)
    
    # Footer
    pdf.set_y(-30)
    pdf.set_font("Arial", "I", 8)
    pdf.cell(0, 10, "This report is generated by LucidAI. For review only.", 0, 0, 'C')
    
    # Sauvegarde
    os.makedirs("reports", exist_ok=True)
    report_path = f"reports/audit_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    pdf.output(report_path)
    
    state['report_path'] = report_path
    return state