from fpdf import FPDF
import os
import datetime

_FONT_CANDIDATES = [
    ("Arial", "B", r"C:\Windows\Fonts\arialbd.ttf"),
    ("Arial", "", r"C:\Windows\Fonts\arial.ttf"),
    ("DejaVuSans", "", r"C:\Windows\Fonts\DejaVuSans.ttf"),
    ("DejaVuSans-Bold", "", r"C:\Windows\Fonts\DejaVuSans-Bold.ttf"),
]


def _clean(text: str) -> str:
    """Rend le texte sûr pour la police helvetica (core font, cp1252)."""
    text = (text or "").replace("€", "EUR")
    return text.encode("cp1252", "replace").decode("cp1252")


def _setup_fonts(pdf: FPDF) -> str:
    """Embarque une vraie police TTF si disponible, sinon repli helvetica."""
    for family, style, path in _FONT_CANDIDATES:
        try:
            if os.path.exists(path):
                pdf.add_font(family, style, path)
        except Exception:
            continue
    if "Arial" in pdf.fonts:
        return "Arial"
    return "helvetica"


def _multi_line(pdf: FPDF, family: str, text: str) -> None:
    """Écrit une ligne en réinitialisant X pour éviter le bug fpdf2
    (multi_cell laisse X en fin de ligne => largeur nulle au tour suivant)."""
    pdf.set_x(pdf.l_margin)
    try:
        pdf.multi_cell(0, 6, _clean(text), align="L")
    except Exception:
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, 6, _clean(text).replace(" ", "_"), align="L")


def officer_node(state: dict):
    anomalies = state.get('anomalies', [])
    risk_score = state.get('risk_score', 0)
    filename = state.get('filename', 'report')

    pdf = FPDF()
    pdf.add_page()
    family = _setup_fonts(pdf)

    # En-tête
    pdf.set_font(family, "B", 16)
    pdf.cell(0, 10, "LucidAI - Audit Report", 0, 1)
    pdf.set_font(family, "I", 10)
    pdf.cell(0, 10, f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1)
    pdf.cell(0, 10, f"Source: {_clean(filename)}", 0, 1)
    pdf.ln(10)

    # Score de risque
    pdf.set_font(family, "B", 14)
    pdf.cell(0, 10, f"Risk Score: {risk_score} / 100", 0, 1)
    pdf.ln(5)

    # Liste des anomalies
    pdf.set_font(family, "B", 12)
    pdf.cell(0, 10, f"Total Anomalies Detected: {len(anomalies)}", 0, 1)
    pdf.ln(5)

    pdf.set_font(family, "", 10)
    for idx, anom in enumerate(anomalies[:20]):  # Max 20 pour le rapport
        sev = str(anom.get('severity', 'unknown')).upper()
        desc = str(anom.get('description', 'No description'))
        _multi_line(pdf, family, f"{idx+1}. [{sev}] {desc}")

    if len(anomalies) > 20:
        pdf.cell(0, 10, f"... and {len(anomalies)-20} more anomalies.", 0, 1)

    # Footer
    pdf.set_y(-30)
    pdf.set_font(family, "I", 8)
    pdf.cell(0, 10, "This report is generated by LucidAI. For review only.", 0, 0, 'C')

    # Sauvegarde
    os.makedirs("reports", exist_ok=True)
    report_path = f"reports/audit_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    pdf.output(report_path)

    state['report_path'] = report_path
    return state
